name: build test

on:
  release:
    types: [published]  # Trigger when a release is published
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Copy output to workspace
      - name: Copy output
        run: |
          ls
          mkdir -p ${{ github.workspace }}/workspace/
          cp foo.txt ${{ github.workspace }}/workspace/
          cp bar.txt ${{ github.workspace }}/workspace/
          cp -rv nested ${{ github.workspace }}/workspace/

      # Upload the output as a release artifact
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ github.workspace }}/workspace/**/*.*
